//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe3D.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBlue")]
        public global::System.Drawing.Color DrawingColor {
            get {
                return ((global::System.Drawing.Color)(this["DrawingColor"]));
            }
            set {
                this["DrawingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84")]
        public double DefaultCellSize {
            get {
                return ((double)(this["DefaultCellSize"]));
            }
            set {
                this["DefaultCellSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DefaultCameraPositionAlongX {
            get {
                return ((double)(this["DefaultCameraPositionAlongX"]));
            }
            set {
                this["DefaultCameraPositionAlongX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DefaultCameraPositionAlongY {
            get {
                return ((double)(this["DefaultCameraPositionAlongY"]));
            }
            set {
                this["DefaultCameraPositionAlongY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public double DefaultCameraPositionAlongZ {
            get {
                return ((double)(this["DefaultCameraPositionAlongZ"]));
            }
            set {
                this["DefaultCameraPositionAlongZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double DistanceToTheNearPlaneOfCamera {
            get {
                return ((double)(this["DistanceToTheNearPlaneOfCamera"]));
            }
            set {
                this["DistanceToTheNearPlaneOfCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public double DistanceToTheFarPlaneOfCamera {
            get {
                return ((double)(this["DistanceToTheFarPlaneOfCamera"]));
            }
            set {
                this["DistanceToTheFarPlaneOfCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.7854")]
        public double DefaultCameraRotationAngleAlongX {
            get {
                return ((double)(this["DefaultCameraRotationAngleAlongX"]));
            }
            set {
                this["DefaultCameraRotationAngleAlongX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.6283")]
        public double DefaultCameraRotationAngleAlongY {
            get {
                return ((double)(this["DefaultCameraRotationAngleAlongY"]));
            }
            set {
                this["DefaultCameraRotationAngleAlongY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.57")]
        public double DefaultCameraRotationAngleAlongZ {
            get {
                return ((double)(this["DefaultCameraRotationAngleAlongZ"]));
            }
            set {
                this["DefaultCameraRotationAngleAlongZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.157")]
        public double CameraRotationAnglePerTimerInterval {
            get {
                return ((double)(this["CameraRotationAnglePerTimerInterval"]));
            }
            set {
                this["CameraRotationAnglePerTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int CameraTransformationIntervalForTimer {
            get {
                return ((int)(this["CameraTransformationIntervalForTimer"]));
            }
            set {
                this["CameraTransformationIntervalForTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double CameraDisplacementAlongZPerTimerInterval {
            get {
                return ((double)(this["CameraDisplacementAlongZPerTimerInterval"]));
            }
            set {
                this["CameraDisplacementAlongZPerTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CameraDisplacementAlongXPerTimerInterval {
            get {
                return ((double)(this["CameraDisplacementAlongXPerTimerInterval"]));
            }
            set {
                this["CameraDisplacementAlongXPerTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CameraDisplacementAlongYPerTimerInterval {
            get {
                return ((double)(this["CameraDisplacementAlongYPerTimerInterval"]));
            }
            set {
                this["CameraDisplacementAlongYPerTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rep")]
        public string ReplayExtension {
            get {
                return ((string)(this["ReplayExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gam")]
        public string UnfinishedGameExtension {
            get {
                return ((string)(this["UnfinishedGameExtension"]));
            }
        }
    }
}
